services:
  db:
    image: postgres:16
    container_name: movyra-postgres-dev
    environment:
      POSTGRES_DB: movyra
      POSTGRES_USER: movyra_app
      POSTGRES_PASSWORD: movyra_dev_pwd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U movyra_app -d movyra"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      QUARKUS_HTTP_PORT: "8080"

      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: movyra_app
      QUARKUS_DATASOURCE_PASSWORD: movyra_dev_pwd
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/movyra

      QUARKUS_FLYWAY_MIGRATE_AT_START: "true"
      QUARKUS_FLYWAY_SCHEMAS: app
      QUARKUS_FLYWAY_DEFAULT_SCHEMA: app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
